apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-teams-filter-get-rolebindings
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-teams-filter-get-rolebindings
subjects:
- kind: ServiceAccount
  name: github-teams-filter-get-rolebindings
  namespace: cloud-platform-github-teams-filter
roleRef:
  kind: ClusterRole
  name: github-teams-filter-get-rolebindings
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-teams-filter-get-rolebindings
  namespace: cloud-platform-github-teams-filter