{{- if .Values.cronjobEnabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: report-unused-sg
spec:
  schedule: {{.Values.cronjobSchedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          containers:
          - image: ministryofjustice/cloud-platform-tools:1.18
            name: cloud-platform-tools
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: secret-access-key
            - name: SLACK_HOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-hook-url
                  key: value
            - name: AWS_DEFAULT_REGION
              value: "eu-west-2"
            command: ["python3"]
            args: ["opt/get-unused-sgs.py"]
            volumeMounts:
            - name: config
              mountPath: /opt/get-unused-sgs.py
              subPath: get-unused-sgs.py
          volumes:
          - name: config
            configMap:
              defaultMode: 0755
              name: get-unused-sgs-cm
          restartPolicy: Never
      backoffLimit: 10  
{{- else }}
apiVersion: batch/v1
kind: Job
metadata: 
  labels:
    app: report-unused-sg
  name: report-unused-sg
spec:
  template:
    spec:
      serviceAccountName: default
      securityContext:
        runAsUser: 1000
      containers: 
      - image: golang:latest
        name: cloud-platform-tools
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: secret-access-key
        - name: SLACK_HOOK_URL
          valueFrom:
            secretKeyRef:
              name: slack-hook-url
              key: value
        - name: AWS_DEFAULT_REGION
          value: "eu-west-2"
        command: ["/bin/sh"]
        args:
        - "-xe"
        - /opt/entrypoint.sh
        volumeMounts:
        - name: config
          mountPath: /opt/unused-sgs.go
          subPath: unused-sgs.go
        - name: config
          mountPath: /opt/entrypoint.sh
          subPath: entrypoint.sh
      volumes:
      - name: config
        configMap:
          defaultMode: 0755
          name: get-unused-sgs-cm
      restartPolicy: OnFailure
  backoffLimit: 10
{{- end }}