# Default values for helm_deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: ministryofjustice/cloud-platform-helloworld-ruby
  tag: 1.2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  port: 4567
  targetPort: 4567

ingress:
  enabled: true
  annotations: {}
  # It can be default(default ingress-controller) or modsec(ingress-controller has the modsec WAF enabled)
  className: ""
  hosts:
    - host: <DNS-PREFIX>.apps.<cluster-name>.cloud-platform.service.justice.gov.uk
      paths: /

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
