{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-ecr-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-ecr-exporter.name" . }}
    chart: {{ template "prometheus-ecr-exporter.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

  annotations:
  {{- if .Values.serviceAccount.annotations }}
    {{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
{{- end }}
