{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "upload-token-s3.serviceAccountName" . }}
  labels:
{{ include "upload-token-s3.labels" . | nindent 4 }}
{{- end -}}
