apiVersion: v1
description: A Helm chart for eventruter (formally https://github.com/heptiolabs/eventrouter)
name: eventrouter
version: 0.3.3
appVersion: 0.3
home: https://github.com/heptiolabs/eventrouter
sources:
- https://github.com/heptiolabs/eventrouter
keywords:
- eventrouter
