apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: token-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: token-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: token-reader
subjects:
- kind: ServiceAccount
  name: upload-token-s3
  namespace: ecr
