name: Keep gh-pages in sync wrt. main

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - run: git checkout -b gh-pages
      - run: git push origin gh-pages --force
