name: Keep gh-pages in sync wrt. main

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: git checkout -b gh-pages
      - run: git push origin gh-pages --force
